### ISSUE TITLE
Documentation on how to test differential amplitude

### ISSUE THREAD

**Issue by lvclark** [ranafi/Scripts-for-Tumor-circadian-clock-strength-influences-metastatic-potential-and-predicts-patient-prog#1]
Hi @JanHammarlund and @ranafi,

I would like to test for differential amplitude between two groups of samples.  I am trying to follow along with `Training_Script_for_Normal_and_Normal_with_Luminal_A_in_Normal_only_EigenSpace_with_and_without_Time_Balance_09_15_2022.jl`, and have made some progress, but it is difficult because there is no documentation, and comments explaining the code are minimal.  I keep running into errors, but on top of that I get nervous blindly running a script that I don't understand.  Would it be possible to provide (either here or in the CYCLOPS 2.0 repository) some instructions?

Thanks,

Lindsay

**Comment by JanHammarlund** [comment]
Hello Lindsay, you're in the repository related to the publication "Tumor circadian clock strength...luminal A breast cancer." The purpose of this repository is to be able to recreate the results from the publication, not to modify the code.

The CYCLOPS 2.0 repository has a quite extensive [README](https://github.com/ranafi/CYCLOPS-2.0). ***For a quick start guide, skip to the 'Packages' section (section 7) and use the provided [template](https://github.com/ranafi/CYCLOPS-2.0/blob/main/CYCLOPS_2_0_Template.jl).***

Testing for differential rhythmicity is outside of the scope of the CYCLOPS 2.0 package. I would recommend using [compareRhythms](https://github.com/bharathananth/compareRhythms) for this purpose.

That said, testing for differential amplitude is an open statistical problem for which no simple solution exists. To test for differential amplitude, one must first approximate the acrophase of a wave using the form:

*expr ~ sin(sample.phases) + cos(sample.phase) + sample.condition + sample.covariates*,

then calculate the acrophase of the wave using the model's sin and cos coefficients (e.g., A & B, respectively):

*acrophase = atan2(A, B)*,

then build the base and nested models using the above-calculated acrophase to test if the sample condition influences transcript amplitude:

base model: *expr ~ cos(sample.phase - acrophase) + sample.condition + sample.covariates*
nested model: *expr ~ sample.condition \* cos(sample.phase - acrophase) + sample.condition + sample.covariates*
test models: *anova(base model, nested model)*

The resulting significance of the ANOVA indicates if *sample.condition* significantly influences transcript amplitude.

**Comment by lvclark** [comment]
Thanks for your quick response!  I thought that you guys tested for differential amplitude in the manuscript and that this was the code used to do that, but I'll just leave it and try compareRhythms if you think that would be more appropriate.
